export enum ROUTE_NAMES {
  app = 'app',
  auth = 'app.auth',
  authKeplr494 = 'app.auth-keplr-494',
  authMnemonic494 = 'app.auth-mnemonic-494',
  accounts = 'app.accounts',
  accountDetails = 'app.accounts.account-details',
  blocks = 'app.blocks',
  blockDetails = 'app.blocks.block-details',
  charts = 'app.charts',
  dataSources = 'app.data-sources',
  dataSourceDetails = 'app.data-sources.data-source-details',
  oracleScripts = 'app.oracle-scripts',
  oracleScriptDetails = 'app.oracle-scripts.oracle-script-details',
  requests = 'app.requests',
  requestDetails = 'app.requests.request-details',
  transactions = 'app.transactions',
  transactionDetails = 'app.transactions.transaction-details',
  validators = 'app.validators',
  validatorDetails = 'app.validators.validator-details',
  governance = 'app.governance',
  proposal = 'app.governance.proposal',
  voting = 'app.governance.proposal.voting',
  wallet = 'app.wallet',
  ibc = 'app.ibc',
}
